"""Tests for training/sample_the_stack.py — The Stack v1 real data sampler."""

import json
import os
import sys
import tempfile
from unittest.mock import MagicMock, patch

import pytest

# Ensure the training directory is importable
sys.path.insert(0, os.path.dirname(__file__))


# ---------------------------------------------------------------------------
# Constants tests
# ---------------------------------------------------------------------------


class TestStackLanguageMap:
    def test_has_14_entries(self):
        from sample_the_stack import STACK_LANGUAGE_MAP

        assert len(STACK_LANGUAGE_MAP) == 14

    def test_all_values_are_category_subtype_tuples(self):
        from sample_the_stack import STACK_LANGUAGE_MAP

        for lang, (category, sub_type) in STACK_LANGUAGE_MAP.items():
            assert isinstance(lang, str)
            assert isinstance(category, str)
            assert isinstance(sub_type, str)

    def test_code_languages_have_code_category(self):
        from sample_the_stack import STACK_LANGUAGE_MAP

        code_langs = [
            "python", "javascript", "typescript", "rust", "go", "java",
            "sql", "shell", "css", "dockerfile", "makefile", "html",
        ]
        for lang in code_langs:
            assert lang in STACK_LANGUAGE_MAP, f"Missing language: {lang}"
            assert STACK_LANGUAGE_MAP[lang][0] == "code", (
                f"{lang} should have category 'code'"
            )

    def test_prose_languages_have_prose_category(self):
        from sample_the_stack import STACK_LANGUAGE_MAP

        assert STACK_LANGUAGE_MAP["markdown"] == ("prose", "markdown")
        assert STACK_LANGUAGE_MAP["tex"] == ("prose", "latex")

    def test_contains_all_expected_languages(self):
        from sample_the_stack import STACK_LANGUAGE_MAP

        expected = {
            "python", "javascript", "typescript", "rust", "go", "java",
            "sql", "shell", "css", "dockerfile", "makefile", "html",
            "markdown", "tex",
        }
        assert set(STACK_LANGUAGE_MAP.keys()) == expected


# ---------------------------------------------------------------------------
# filter_sample tests
# ---------------------------------------------------------------------------


class TestFilterSample:
    def test_rejects_too_few_lines(self):
        from sample_the_stack import filter_sample

        content = "line1\nline2\nline3\nline4\n"
        assert filter_sample(content) is False

    def test_rejects_too_many_lines(self):
        from sample_the_stack import filter_sample

        content = "\n".join(f"line {i}" for i in range(501))
        assert filter_sample(content) is False

    def test_rejects_auto_generated_code_generated(self):
        from sample_the_stack import filter_sample

        content = "// Code generated by protoc-gen-go. DO NOT EDIT.\n" + "\n".join(
            f"func f{i}() {{}}" for i in range(10)
        )
        assert filter_sample(content) is False

    def test_rejects_auto_generated_hash_auto(self):
        from sample_the_stack import filter_sample

        content = "# AUTO-GENERATED FILE\n" + "\n".join(
            f"item_{i} = {i}" for i in range(10)
        )
        assert filter_sample(content) is False

    def test_rejects_auto_generated_c_style(self):
        from sample_the_stack import filter_sample

        content = "/* AUTO GENERATED */\n" + "\n".join(
            f"int x{i} = {i};" for i in range(10)
        )
        assert filter_sample(content) is False

    def test_rejects_auto_generated_this_file_is(self):
        from sample_the_stack import filter_sample

        content = "# This file is auto-generated\n" + "\n".join(
            f"val_{i} = {i}" for i in range(10)
        )
        assert filter_sample(content) is False

    def test_rejects_auto_generated_do_not_edit(self):
        from sample_the_stack import filter_sample

        content = "// DO NOT EDIT\n" + "\n".join(
            f"const x{i} = {i};" for i in range(10)
        )
        assert filter_sample(content) is False

    def test_rejects_binary_content(self):
        from sample_the_stack import filter_sample

        # 15% non-printable characters
        printable = "a" * 85 + "\n" * 10
        non_printable = "\x00" * 15
        content = printable + non_printable
        # Ensure at least 5 non-empty lines
        content = "\n".join(["normal line"] * 10) + "\n" + "\x00" * 20
        assert filter_sample(content) is False

    def test_accepts_valid_code(self):
        from sample_the_stack import filter_sample

        content = "\n".join([
            "def hello():",
            '    print("Hello, world!")',
            "",
            "def goodbye():",
            '    print("Goodbye!")',
            "",
            "if __name__ == '__main__':",
            "    hello()",
            "    goodbye()",
            "",
        ])
        assert filter_sample(content) is True

    def test_accepts_exactly_5_non_empty_lines(self):
        from sample_the_stack import filter_sample

        content = "\n".join([
            "line 1",
            "line 2",
            "line 3",
            "line 4",
            "line 5",
        ])
        assert filter_sample(content) is True

    def test_accepts_exactly_500_lines(self):
        from sample_the_stack import filter_sample

        content = "\n".join(f"line {i}" for i in range(500))
        assert filter_sample(content) is True


# ---------------------------------------------------------------------------
# compute_length_bucket tests
# ---------------------------------------------------------------------------


class TestComputeLengthBucket:
    def test_short_bucket(self):
        from sample_the_stack import compute_length_bucket

        content = "\n".join(f"line {i}" for i in range(5))
        assert compute_length_bucket(content) == "short"

    def test_short_boundary_9_lines(self):
        from sample_the_stack import compute_length_bucket

        content = "\n".join(f"line {i}" for i in range(9))
        assert compute_length_bucket(content) == "short"

    def test_medium_boundary_10_lines(self):
        from sample_the_stack import compute_length_bucket

        content = "\n".join(f"line {i}" for i in range(10))
        assert compute_length_bucket(content) == "medium"

    def test_medium_bucket(self):
        from sample_the_stack import compute_length_bucket

        content = "\n".join(f"line {i}" for i in range(30))
        assert compute_length_bucket(content) == "medium"

    def test_medium_boundary_50_lines(self):
        from sample_the_stack import compute_length_bucket

        content = "\n".join(f"line {i}" for i in range(50))
        assert compute_length_bucket(content) == "medium"

    def test_long_bucket(self):
        from sample_the_stack import compute_length_bucket

        content = "\n".join(f"line {i}" for i in range(51))
        assert compute_length_bucket(content) == "long"

    def test_ignores_empty_lines(self):
        from sample_the_stack import compute_length_bucket

        # 5 non-empty + many empty = should be short
        content = "\n".join(["line"] * 5 + [""] * 50)
        assert compute_length_bucket(content) == "short"


# ---------------------------------------------------------------------------
# sample_language tests (mocked dataset)
# ---------------------------------------------------------------------------


class TestSampleLanguage:
    def _make_mock_dataset(self, items):
        """Create a mock streaming dataset that yields items."""
        mock_ds = MagicMock()
        mock_ds.shuffle.return_value = iter(items)
        return mock_ds

    def test_returns_list_of_dicts(self):
        from sample_the_stack import sample_language

        items = [
            {"content": "\n".join(f"line {i}" for i in range(20))}
            for _ in range(5)
        ]
        with patch("sample_the_stack.datasets") as mock_datasets:
            mock_ds = self._make_mock_dataset(items)
            mock_datasets.load_dataset.return_value = mock_ds
            results = sample_language("python", "code", "python", count=3, seed=42)

        assert isinstance(results, list)
        assert len(results) == 3

    def test_provenance_fields_present(self):
        from sample_the_stack import sample_language

        items = [
            {"content": "\n".join(f"line {i}" for i in range(20))}
            for _ in range(5)
        ]
        with patch("sample_the_stack.datasets") as mock_datasets:
            mock_ds = self._make_mock_dataset(items)
            mock_datasets.load_dataset.return_value = mock_ds
            results = sample_language("python", "code", "python", count=1, seed=42)

        sample = results[0]
        required_fields = [
            "text", "expected_category", "sub_type", "boundary_pair",
            "model", "temperature", "prompt_template", "content_domain",
            "length_bucket", "reasoning_mode",
        ]
        for field in required_fields:
            assert field in sample, f"Missing provenance field: {field}"

    def test_provenance_field_values(self):
        from sample_the_stack import sample_language

        items = [
            {"content": "\n".join(f"line {i}" for i in range(20))}
            for _ in range(5)
        ]
        with patch("sample_the_stack.datasets") as mock_datasets:
            mock_ds = self._make_mock_dataset(items)
            mock_datasets.load_dataset.return_value = mock_ds
            results = sample_language("python", "code", "python", count=1, seed=42)

        sample = results[0]
        assert sample["expected_category"] == "code"
        assert sample["sub_type"] == "python"
        assert sample["boundary_pair"] is None
        assert sample["model"] == "real/the-stack-v1"
        assert sample["temperature"] is None
        assert sample["prompt_template"] is None
        assert sample["content_domain"] == "python"
        assert sample["length_bucket"] in ("short", "medium", "long")
        assert sample["reasoning_mode"] is False

    def test_filters_out_bad_samples(self):
        from sample_the_stack import sample_language

        # Mix of good and bad items
        good_content = "\n".join(f"line {i}" for i in range(20))
        bad_content = "too\nshort"  # < 5 non-empty lines
        items = [
            {"content": bad_content},
            {"content": bad_content},
            {"content": good_content},
            {"content": good_content},
        ]
        with patch("sample_the_stack.datasets") as mock_datasets:
            mock_ds = self._make_mock_dataset(items)
            mock_datasets.load_dataset.return_value = mock_ds
            results = sample_language("python", "code", "python", count=2, seed=42)

        assert len(results) == 2

    def test_calls_load_dataset_correctly(self):
        from sample_the_stack import sample_language

        items = [
            {"content": "\n".join(f"line {i}" for i in range(20))}
            for _ in range(3)
        ]
        with patch("sample_the_stack.datasets") as mock_datasets:
            mock_ds = self._make_mock_dataset(items)
            mock_datasets.load_dataset.return_value = mock_ds
            sample_language("python", "code", "python", count=1, seed=42)

        mock_datasets.load_dataset.assert_called_once_with(
            "bigcode/the-stack",
            data_dir="data/python",
            streaming=True,
            split="train",
        )


# ---------------------------------------------------------------------------
# CLI tests
# ---------------------------------------------------------------------------


class TestCLI:
    def test_build_parser_defaults(self):
        from sample_the_stack import build_parser

        parser = build_parser()
        args = parser.parse_args([])
        assert args.output == "data/source/real/real_samples.jsonl"
        assert args.per_language == 1800
        assert args.seed == 42
        assert args.dry_run is False
        assert args.languages is None

    def test_custom_output(self):
        from sample_the_stack import build_parser

        parser = build_parser()
        args = parser.parse_args(["--output", "/tmp/foo.jsonl"])
        assert args.output == "/tmp/foo.jsonl"

    def test_per_language_flag(self):
        from sample_the_stack import build_parser

        parser = build_parser()
        args = parser.parse_args(["--per-language", "500"])
        assert args.per_language == 500

    def test_seed_flag(self):
        from sample_the_stack import build_parser

        parser = build_parser()
        args = parser.parse_args(["--seed", "123"])
        assert args.seed == 123

    def test_dry_run_flag(self):
        from sample_the_stack import build_parser

        parser = build_parser()
        args = parser.parse_args(["--dry-run"])
        assert args.dry_run is True

    def test_languages_filter(self):
        from sample_the_stack import build_parser

        parser = build_parser()
        args = parser.parse_args(["--languages", "python,rust,go"])
        assert args.languages == "python,rust,go"


class TestLanguagesFilter:
    def test_filters_to_specified_languages(self):
        from sample_the_stack import STACK_LANGUAGE_MAP, _parse_languages

        selected = _parse_languages("python,rust", STACK_LANGUAGE_MAP)
        assert set(selected) == {"python", "rust"}

    def test_all_languages_when_none(self):
        from sample_the_stack import STACK_LANGUAGE_MAP, _parse_languages

        selected = _parse_languages(None, STACK_LANGUAGE_MAP)
        assert set(selected) == set(STACK_LANGUAGE_MAP.keys())

    def test_invalid_language_raises(self):
        from sample_the_stack import STACK_LANGUAGE_MAP, _parse_languages

        with pytest.raises(ValueError, match="Unknown language"):
            _parse_languages("python,cobol", STACK_LANGUAGE_MAP)


# ---------------------------------------------------------------------------
# Dry-run integration test
# ---------------------------------------------------------------------------


class TestDryRun:
    def test_dry_run_prints_plan_no_output_file(self, capsys):
        from sample_the_stack import main

        with tempfile.TemporaryDirectory() as tmpdir:
            output = os.path.join(tmpdir, "test.jsonl")
            main(["--output", output, "--dry-run"])
            captured = capsys.readouterr()
            assert "DRY RUN" in captured.out
            assert not os.path.exists(output)

    def test_dry_run_shows_language_plan(self, capsys):
        from sample_the_stack import main

        with tempfile.TemporaryDirectory() as tmpdir:
            output = os.path.join(tmpdir, "test.jsonl")
            main(["--output", output, "--dry-run"])
            captured = capsys.readouterr()
            assert "python" in captured.out.lower()
            assert "14" in captured.out or "languages" in captured.out.lower()

    def test_dry_run_with_language_filter(self, capsys):
        from sample_the_stack import main

        with tempfile.TemporaryDirectory() as tmpdir:
            output = os.path.join(tmpdir, "test.jsonl")
            main(["--output", output, "--dry-run", "--languages", "python,rust"])
            captured = capsys.readouterr()
            assert "python" in captured.out.lower()
            assert "rust" in captured.out.lower()
            # Should show 2 languages, not 14
            assert "2 languages" in captured.out.lower() or "2" in captured.out


# ---------------------------------------------------------------------------
# sample_all tests (mocked)
# ---------------------------------------------------------------------------


class TestSampleAll:
    def test_writes_jsonl_output(self):
        from sample_the_stack import sample_all

        good_content = "\n".join(f"line {i}" for i in range(20))

        with patch("sample_the_stack.datasets") as mock_datasets:
            mock_ds = MagicMock()
            items = [{"content": good_content} for _ in range(10)]
            mock_ds.shuffle.return_value = iter(items)
            mock_datasets.load_dataset.return_value = mock_ds

            with tempfile.TemporaryDirectory() as tmpdir:
                output = os.path.join(tmpdir, "test.jsonl")
                sample_all(
                    output_path=output,
                    per_language=2,
                    seed=42,
                    languages=["python"],
                )
                assert os.path.exists(output)
                with open(output) as f:
                    lines = [line.strip() for line in f if line.strip()]
                assert len(lines) == 2
                sample = json.loads(lines[0])
                assert sample["expected_category"] == "code"
                assert sample["sub_type"] == "python"
